### ISSUE TITLE
Cannot find module '.'

### ISSUE THREAD

**Issue by tkadlec** [nature/webpagetest-mapper#3]
I installed using npm, but running it from the command line is returning the following error:

```
module.js:338
    throw err;
          ^
Error: Cannot find module '.'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpagetest-mapper/src/cli.js:29:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by philbooth** [comment]
Oh dear, stupidly I've only been running it directly from the git repo until now.

Anyway, I've fixed it and published to npm as version 0.0.2. Thanks heaps for reporting it. :)
